---
galaxy_info:
  author: jason
  description: Install and configure Prometheus and Grafana monitoring stack
  company: "Personal"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - monitoring
    - prometheus
    - grafana
    - metrics

dependencies: []
