---
galaxy_info:
  author: jason
  description: Install and configure MQTT reporter service for Raspberry Pi
  company: "Personal"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - mqtt
    - reporting
    - raspberrypi
    - iot

dependencies: []
