---
galaxy_info:
  author: your_name
  description: Install common packages and perform system updates
  company: "Personal"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - packages
    - apt

dependencies: []
